name: running thw sample workflow
run-name: Running your first github action
on:
 push:
  branches:
   - "feature/**"
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: "first step"
     run: echo ${{ github.actor }}
   - name: Setup Node.js environment
     uses: actions/setup-node@v3.4.1
     with:
       node-version: 14.x
   - name: "final step"
     run: echo "build completed"
   
